import type { WidgetVisualConfig } from '../types/widgetTemplate'
import { defaultWidgetVisualConfig } from '../types/widgetTemplate'

export type WidgetPresetTemplate = {
  id: string
  name: string
  description: string
  category: 'conversion' | 'engagement' | 'promotion' | 'notification' | 'content'
  config: WidgetVisualConfig
}

const base = defaultWidgetVisualConfig

const presets: WidgetPresetTemplate[] = [
  // ── Conversion ──
  {
    id: 'modern-offer',
    name: 'Oferta Moderna',
    description: 'Card limpo com imagem lateral e CTA direto',
    category: 'conversion',
    config: {
      ...base,
      layout: 'media-left',
      variant: 'modern',
      mediaType: 'image',
      backgroundColor: '#ffffff',
      textColor: '#0f172a',
      buttonColor: '#2563eb',
      borderColor: '#e2e8f0',
      borderRadius: 16,
      shadow: 'md',
      padding: 24,
      width: 620,
      minHeight: 260,
    },
  },
  {
    id: 'premium-upsell',
    name: 'Upsell Premium',
    description: 'Visual escuro sofisticado para produtos de alto valor',
    category: 'conversion',
    config: {
      ...base,
      layout: 'media-left',
      variant: 'premium',
      mediaType: 'image',
      backgroundColor: '#020617',
      textColor: '#f1f5f9',
      buttonColor: '#f59e0b',
      borderColor: '#1e293b',
      borderRadius: 20,
      shadow: 'lg',
      padding: 28,
      width: 640,
      minHeight: 280,
    },
  },
  {
    id: 'compact-cta',
    name: 'CTA Compacto',
    description: 'Formato horizontal compacto ideal para inline',
    category: 'conversion',
    config: {
      ...base,
      layout: 'banner',
      variant: 'modern',
      mediaType: 'image',
      showDescription: false,
      showSubtitle: false,
      showComplementaryText: false,
      backgroundColor: '#ffffff',
      textColor: '#0f172a',
      buttonColor: '#16a34a',
      borderColor: '#e2e8f0',
      borderRadius: 999,
      shadow: 'sm',
      padding: 16,
      width: 580,
      minHeight: 120,
      mediaSize: 25,
    },
  },
  // ── Engagement ──
  {
    id: 'glass-popup',
    name: 'Popup Glass',
    description: 'Modal com efeito vidro fosco e destaque visual',
    category: 'engagement',
    config: {
      ...base,
      layout: 'modal',
      variant: 'glass',
      mediaType: 'image',
      backgroundColor: '#1e293b',
      textColor: '#f8fafc',
      buttonColor: '#6366f1',
      borderColor: 'rgba(148,163,184,0.2)',
      borderRadius: 24,
      shadow: 'lg',
      padding: 32,
      width: 520,
      minHeight: 340,
    },
  },
  {
    id: 'video-showcase',
    name: 'Vitrine de Vídeo',
    description: 'Foco em vídeo com texto de suporte e CTA',
    category: 'engagement',
    config: {
      ...base,
      layout: 'video-text',
      variant: 'modern',
      mediaType: 'video',
      showMedia: true,
      backgroundColor: '#ffffff',
      textColor: '#0f172a',
      buttonColor: '#dc2626',
      borderColor: '#e2e8f0',
      borderRadius: 16,
      shadow: 'md',
      padding: 24,
      width: 560,
      minHeight: 360,
      mediaSize: 55,
    },
  },
  {
    id: 'card-vertical-clean',
    name: 'Card Vertical',
    description: 'Card empilhado com visual limpo e moderno',
    category: 'engagement',
    config: {
      ...base,
      layout: 'card-vertical',
      variant: 'minimal',
      mediaType: 'image',
      backgroundColor: '#ffffff',
      textColor: '#334155',
      buttonColor: '#0ea5e9',
      borderColor: '#e2e8f0',
      borderRadius: 12,
      shadow: 'sm',
      padding: 20,
      width: 400,
      minHeight: 380,
      mediaSize: 50,
    },
  },
  // ── Promotion ──
  {
    id: 'flash-sale',
    name: 'Flash Sale',
    description: 'Visual agressivo e chamativo para promoções relâmpago',
    category: 'promotion',
    config: {
      ...base,
      layout: 'media-top',
      variant: 'promotional',
      mediaType: 'image',
      backgroundColor: '#fef3c7',
      textColor: '#78350f',
      buttonColor: '#dc2626',
      borderColor: '#fbbf24',
      borderRadius: 16,
      shadow: 'md',
      padding: 24,
      width: 480,
      minHeight: 340,
    },
  },
  {
    id: 'bold-promo',
    name: 'Promoção Bold',
    description: 'Bloco escuro e marcante com tipografia forte',
    category: 'promotion',
    config: {
      ...base,
      layout: 'promo-block',
      variant: 'bold',
      mediaType: 'image',
      backgroundColor: '#0f172a',
      textColor: '#f8fafc',
      buttonColor: '#ef4444',
      borderColor: '#1e293b',
      borderRadius: 0,
      shadow: 'lg',
      padding: 28,
      width: 640,
      minHeight: 260,
      mediaSize: 40,
    },
  },
  {
    id: 'seasonal-banner',
    name: 'Banner Sazonal',
    description: 'Banner horizontal perfeito para promoções sazonais',
    category: 'promotion',
    config: {
      ...base,
      layout: 'banner',
      variant: 'promotional',
      mediaType: 'image',
      showSubtitle: false,
      showComplementaryText: false,
      backgroundColor: '#fef2f2',
      textColor: '#991b1b',
      buttonColor: '#dc2626',
      borderColor: '#fecaca',
      borderRadius: 999,
      shadow: 'sm',
      padding: 18,
      width: 680,
      minHeight: 120,
      mediaSize: 20,
    },
  },
  // ── Notification ──
  {
    id: 'toast-minimal',
    name: 'Toast Discreto',
    description: 'Notificação compacta de canto, discreta e eficaz',
    category: 'notification',
    config: {
      ...base,
      layout: 'toast',
      variant: 'minimal',
      mediaType: 'image',
      showDescription: false,
      showComplementaryText: false,
      showBadge: false,
      backgroundColor: '#ffffff',
      textColor: '#334155',
      buttonColor: '#2563eb',
      borderColor: '#e2e8f0',
      borderRadius: 14,
      shadow: 'md',
      padding: 16,
      width: 360,
      minHeight: 110,
      mediaSize: 30,
    },
  },
  {
    id: 'toast-dark',
    name: 'Toast Escuro',
    description: 'Notificação compacta com visual escuro premium',
    category: 'notification',
    config: {
      ...base,
      layout: 'toast',
      variant: 'premium',
      mediaType: 'image',
      showDescription: false,
      showComplementaryText: false,
      showBadge: false,
      backgroundColor: '#0f172a',
      textColor: '#e2e8f0',
      buttonColor: '#f59e0b',
      borderColor: '#1e293b',
      borderRadius: 14,
      shadow: 'lg',
      padding: 16,
      width: 360,
      minHeight: 110,
      mediaSize: 30,
    },
  },
  // ── Content ──
  {
    id: 'image-hero',
    name: 'Imagem Hero',
    description: 'Imagem em destaque com foco visual total',
    category: 'content',
    config: {
      ...base,
      layout: 'image-button',
      variant: 'modern',
      mediaType: 'image',
      showMedia: true,
      showSubtitle: false,
      showDescription: false,
      showComplementaryText: false,
      backgroundColor: '#ffffff',
      textColor: '#0f172a',
      buttonColor: '#2563eb',
      borderColor: '#e2e8f0',
      borderRadius: 16,
      shadow: 'md',
      padding: 20,
      width: 480,
      minHeight: 320,
    },
  },
  {
    id: 'text-minimal',
    name: 'Texto Puro',
    description: 'Somente texto, ideal para mensagens e avisos',
    category: 'content',
    config: {
      ...base,
      layout: 'text-only',
      variant: 'minimal',
      mediaType: 'none',
      showMedia: false,
      backgroundColor: '#f8fafc',
      textColor: '#334155',
      buttonColor: '#475569',
      borderColor: '#e2e8f0',
      borderRadius: 12,
      shadow: 'none',
      padding: 24,
      width: 480,
      minHeight: 180,
    },
  },
  {
    id: 'card-horizontal-modern',
    name: 'Card Horizontal',
    description: 'Card largo e moderno para destaque lateral',
    category: 'content',
    config: {
      ...base,
      layout: 'card-horizontal',
      variant: 'modern',
      mediaType: 'image',
      backgroundColor: '#ffffff',
      textColor: '#0f172a',
      buttonColor: '#7c3aed',
      borderColor: '#e2e8f0',
      borderRadius: 18,
      shadow: 'md',
      padding: 24,
      width: 640,
      minHeight: 240,
      mediaSize: 38,
    },
  },
]

export const widgetPresetTemplates = presets

export const presetCategories = [
  { id: 'all' as const, label: 'Todos' },
  { id: 'conversion' as const, label: 'Conversão' },
  { id: 'engagement' as const, label: 'Engajamento' },
  { id: 'promotion' as const, label: 'Promoção' },
  { id: 'notification' as const, label: 'Notificação' },
  { id: 'content' as const, label: 'Conteúdo' },
]

export type PresetCategoryFilter = 'all' | WidgetPresetTemplate['category']

export const getPresetsByCategory = (category: PresetCategoryFilter) =>
  category === 'all' ? presets : presets.filter((p) => p.category === category)
